on: [push]
jobs:
   custom_test:
     runs-on: ubuntu-latest
     name: we are tesings
     steps:
       - name: get pokemon namen
         uses: TamminaRajasekhar/Demo-Actions@main
         id: pokemon
         with:
           pokemon_id: 150
       - name: get the pokemon
         run: echo "${{steps.pokemon.outputs.pokemon_name}} attack"
